server:
  port: 8085


eureka:
  instance:
    hostname: http://localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka/
      cache-refresh-interval: 10

spring:
  application:
    name: CORE-BANKING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bankingDB?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: System@25
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

openapi:
  service:
    title: core-service doc
    contact: nitinkumar@javaverse.com
    version: 1.0.0
    license-name: Java-verse License
    license-url: http://javaverse.com/license
    description: This is Core Service, which is responsible for managing all core banking related operations
    server-url: http://localhost:8082 # api gateway url
    server-description: Banking App Server
    terms-of-service-url: http://javaverse.com/terms/

springdoc:
  api-docs:
    path: /core-banking-service/v3/api-docs
  swagger-ui:
    path: /core-banking-service/swagger-ui.html

# ===============================
# = JWT TOKEN
#   admin / secret / alg - SHA256
# ===============================
security:
  jwt:
    secret-key: 1fd849baf9cc24c3c13f83005d8c2072c844e426458480e8e9d47aea721a748c
    expiration-time: 3600000 # 1 hour