server:
  port: 8082

spring:
  application:
    name: API-GATEWAY

  eureka:
    instance:
      hostname: http://localhost
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${spring.eureka.instance.hostname}:8761/eureka/
        cache-refresh-interval: 10