name: Build and Deploy Banking App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
jobs:
  build-deploy:
    name: Build and Deploy Banking App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run tests
        run: mvn -B test

      - name: Build with Maven
        run:
          mvn clean
          mvn -B install



