server:
  port: 8084

spring:
    application:
        name: USER-SERVICE

    eureka:
        instance:
        hostname: http://localhost
        client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${spring.eureka.instance.hostname}:8761/eureka/
            cache-refresh-interval: 10

    datasource:
      url: jdbc:postgresql://localhost:5432/
      username: postgres
      password: System@25
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
