server:
  port: 8084

eureka:
  instance:
    hostname: http://localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.instance.hostname}:8761/eureka/
      cache-refresh-interval: 10

spring:
    application:
        name: USER-SERVICE

    datasource:
      url: jdbc:postgresql://localhost:5432/bankingDB?createDatabaseIfNotExist=true&useSSL=false
      username: postgres
      password: System@25
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

openapi:
  service:
    title: user-service doc
    contact: nitinkumar@javaverse.com
    version: 1.0.0
    license: 1.0.0
    description: This is User Service, which is responsible for managing user's related operations
    url: http://localhost:8082 # api gateway url
    terms-of-service: http://localhost:8082

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html