# Spring Boot application configuration for production environment
spring:
  datasource:
    url: jdbc:postgresql://${AWS_DATABASE_URL}:5432/bankingDB?createDatabaseIfNotExist=true&useSSL=false
    username: ${AWS_DATABASE_USERNAME}
    password: ${AWS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

eureka:
  instance:
    hostname: DISCOVERY-SERVICE
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      cache-refresh-interval: 10
