name: Build and Deploy Discovery Server
on:
  push:
    branches:
      - main
    paths:
      - 'discovery-server/**' # Trigger on changes in feature branch for discovery-server
  pull_request:
    branches:
      - main
    paths:
      - 'discovery-server/**' # Trigger on pull requests to main branch for discovery-server

jobs:
  build:
    name: Build Discovery Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven # Cache Maven dependencies

      - name: Build with Maven
        run: mvn -B package --file discovery-server/pom.xml

      - name: Run tests
        run: mvn -B test --file discovery-server/pom.xml

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: discovery-server
          file: ./discovery-server/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-server:latest

  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: discovery-server
          file: ./discovery-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-server:latest