name: Build and Deploy User Service
on:
  push:
    paths:
      - 'user-service/**' # Trigger on changes in user-service
    branches:
      - main # Trigger on the main branch
  pull_request:
    paths:
      - 'user-service/**' # Trigger on pull requests to the main branch for user-service
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-deploy:
    name: Build and Deploy Banking App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven # Cache Maven dependencies

      - name: Build with Maven
        run: mvn -B package -DskipTests --file user-service/pom.xml

      - name: Run tests
        run: mvn -B test --file user-service/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: user-service
          file: ./user-service/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: user-service
          file: ./user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest



