name: Build and Deploy Banking App
on:
  push:
    paths:
      - 'user-service/**' # Trigger on changes in user-service

jobs:
  build-deploy:
    name: Build and Deploy Banking App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install user-service/pom.xml

      - name: Run tests
        run: mvn test user-service/pom.xml



