name: Build and Deploy User Service
on:
  push:
    paths:
      - 'user-service/**' # Trigger on changes in user-service
    branches:
      - main # Trigger on the main branch
  pull_request:
    paths:
      - 'user-service/**' # Trigger on pull requests to the main branch for user-service
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    name: Build User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven # Cache Maven dependencies

      - name: Build with Maven
        run: mvn -B package -DskipTests --file user-service/pom.xml

      - name: Run tests
        run: mvn -B test --file user-service/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: user-service
          file: ./user-service/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: user-service
          file: ./user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

  deploy:
    needs: build
    name: Deploy User Service to AWS ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: user-service/ecs-task-definition.json
          service: user-service-service-2ltillfj
          cluster: user-service-cluster
          wait-for-service-stability: true
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest



